// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nvRDx8NY24Q9qsluKAXL4QIckfFN8aI',
    appId: '1:716168221491:web:3b7c958e8faf7050f4e446',
    messagingSenderId: '716168221491',
    projectId: 'epicare-v1',
    authDomain: 'epicare-v1.firebaseapp.com',
    storageBucket: 'epicare-v1.firebasestorage.app',
    measurementId: 'G-L064Y9ZCTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVOKWPCPrdRuOIuLnRuudMhAwAJGIHUiY',
    appId: '1:716168221491:android:709b5f048cd819b7f4e446',
    messagingSenderId: '716168221491',
    projectId: 'epicare-v1',
    storageBucket: 'epicare-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgLu1NkZQ8noQbQ5sE9WMkCYnRaQAGaJQ',
    appId: '1:716168221491:ios:4f8b4acfe6a5133af4e446',
    messagingSenderId: '716168221491',
    projectId: 'epicare-v1',
    storageBucket: 'epicare-v1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgLu1NkZQ8noQbQ5sE9WMkCYnRaQAGaJQ',
    appId: '1:716168221491:ios:4f8b4acfe6a5133af4e446',
    messagingSenderId: '716168221491',
    projectId: 'epicare-v1',
    storageBucket: 'epicare-v1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
